tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

brew "htop"
brew "hub"
brew "jq"
brew "nvm"
brew "parallel"
brew "postgresql", restart_service: true
brew "tig"
brew "tmux"
brew "tree"
brew "wget"
brew "zsh-autosuggestions"
brew "zsh-completions"

cask "amethyst"
cask "firefox"
cask "font-fira-code"
cask "google-chrome"
cask "spotify"
cask "visual-studio-code"
cask "webstorm"
