[colors.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[colors.cursor]
cursor = "#657b83"
text = "#fdf6e3"

[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[colors.primary]
background = "#fdf6e3"
foreground = "#657b83"

[cursor]
style.blinking = "Always"
blink_interval = 500

[font]
size = 16.0

[font.normal]
family = "Cascadia Code PL"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = 0
mods = "Command"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "Up"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "Down"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[window]
decorations = "transparent"

[window.padding]
x = 8
y = 30
